openapi: 3.0.3
info:
  title: API ZF[pro]Parts Ping
  version: 1.0.0
  description: |
    Endpoint related to [pro]Parts API ping

    Used for health check of API status
servers:
  - url: https://glue-backend.marketplace.mmm.azure.zf.com
    description: Staging environment
  - url: https://api.pro-parts.com/retailer/v1
    description: Production environment
paths:
  /ping:
    get:
      description: Used to check the health status of all APIs.
      parameters:
        - name: client_id
          in: header
          description: The Client-ID of the Application.
          required: true
          schema:
            type: string
        - name: client_secret
          in: header
          description: The Client-Secret of Application.
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful Health Check Response
          content:
            application/json:
              schema:
                required:
                  - apiName
                  - apiVersion
                  - status
                type: object
                properties:
                  apiVersion:
                    type: string
                    example: 1.0.0
                  apiName:
                    type: string
                  status:
                    type: string
                    example: UP
                description: The health check response model
                example:
                  status: UP
                  apiName: zfmb-el-retailer-api
                  apiVersion: 1.0.0
      summary: /ping
      operationId: get_ping
components:
x-original-swagger-version: '2.0'
